apiVersion: batch/v1
kind: CronJob
metadata:
  name: analyzer

spec:
  schedule: 30 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: analyzer
              image: registry.home.dennisskoko.com/falukollen/analyzer:latest
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ['ALL']
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                seccompProfile:
                  type: RuntimeDefault
              env:
                - name: APP_STORAGE_FOLDER
                  value: /etc/falukollen
              volumeMounts:
                - name: storage
                  mountPath: /etc/falukollen
          volumes:
            - name: storage
              nfs:
                server: storage.lan
                path: /mnt/main/services/falukollen
